[build]
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# API redirects for functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Enable Next.js plugin for proper SSR support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000