[build]
  command = "rm -rf .next/cache && next build"
  publish = ".next"

# Enable Next.js plugin for proper SSR support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000